# Generated by Django 4.2.3 on 2023-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_puntodeinteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeinteres',
            name='tipo_amenidad',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
