# Generated by Django 4.2.3 on 2023-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_puntodeinteres_enlace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntodeinteres',
            name='datos_adicionales',
        ),
        migrations.AddField(
            model_name='puntodeinteres',
            name='icono',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
