# Generated by Django 4.2.3 on 2023-09-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_puntodeinteres_datos_adicionales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeinteres',
            name='icono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
