# Generated by Django 4.2.3 on 2023-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_puntodeinteres_icono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeinteres',
            name='datos_adicionales',
            field=models.JSONField(default='None', max_length=100),
        ),
    ]
