# Generated by Django 4.2.3 on 2023-09-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_puntodeinteres_datos_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeinteres',
            name='datos_adicionales',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
