# Generated by Django 4.2.3 on 2023-09-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aparcamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeinteres',
            name='accesibilidad',
            field=models.CharField(choices=[('yes', 'Yes'), ('limited', 'Limited'), ('no', 'No'), ('designated', 'Designated')], default='no', max_length=10),
        ),
    ]
