# Generated by Django 4.2.3 on 2023-09-22 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_puntousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntousuario',
            name='descripcion',
            field=models.TextField(default='Desconocida'),
        ),
        migrations.AddField(
            model_name='puntousuario',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='puntousuario',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
