# Generated by Django 4.2.3 on 2023-09-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_puntodeinteres_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puntousuario',
            unique_together={('latitud', 'longitud')},
        ),
    ]
